### ISSUE TITLE
Passive life regen

### ISSUE THREAD

**Issue by ttamttamS** [thebrightspark/No.-Lives#2]
It would be great to have a config setting that adds lives on a timer up to a set value. This way players would be encouraged to play more carefully but it wouldn't be as punishing as a ban or as complicated as creating 1-ups. Sorry for the double issue but this felt sufficiently different from my other issue.

**Comment by thebrightspark** [comment]
Hmm sure why not 🤷‍♂️

**Comment by thebrightspark** [comment]
Added in commit https://github.com/thebrightspark/No.-Lives/commit/ea81befa931e2f68585ad4931fb712926ee7ca97
It'll be in the next release
