### ISSUE TITLE
Crashes server after world loading with no crash report, but gives console lines.

### ISSUE THREAD

**Issue by Darkmega18** [thebrightspark/No.-Lives#3]
Just, uh, this is from a multicraft console, so it sorta goes upside down going upwards rather than top to bottom. But hopefully you can see into this.

05.07 03:53:48 [Server] INFO at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?] 05.07 03:53:48 [Server] INFO at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?] 05.07 03:53:48 [Server] INFO at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?] 05.07 03:53:48 [Server] INFO at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?] 05.07 03:53:48 [Server] INFO at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?] 05.07 03:53:48 [Server] INFO at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?] 05.07 03:53:48 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161] 05.07 03:53:48 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161] 05.07 03:53:48 [Server] INFO at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?] 05.07 03:53:48 [Server] INFO at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627) ~[forge-1.12.2-14.23.4.2705-universal.jar:?] 05.07 03:53:48 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161] 05.07 03:53:48 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161] 05.07 03:53:48 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161] 05.07 03:53:48 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] 05.07 03:53:48 [Server] INFO at brightspark.nolives.NoLives.serverStarting(NoLives.java:77) ~[NoLives.class:?] 05.07 03:53:48 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.server.MinecraftServer.func_71221_J()Ljava/lang/String; 05.07 03:53:48 [Server] INFO net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from No. Lives (nolives) 05.07 03:53:48 [Server] Server thread/ERROR [FML]: A fatal exception occurred during the server starting event

**Comment by thebrightspark** [comment]
Ah looks like I can't get the world name on a server... Must have slipped through my testing.

I'll get this fixed soon, thanks for reporting!

**Comment by Darkmega18** [comment]
no problemo. glad to help. :)

**Comment by thebrightspark** [comment]
Fixed in commit https://github.com/thebrightspark/No.-Lives/commit/a31c28c5f3d56b7e32f9477d3c5f5b240d2c3e5d
