### ISSUE TITLE
Double life loss with Hardcore Revival

### ISSUE THREAD

**Issue by build2stone** [thebrightspark/No.-Lives#4]
Hardcore Revival provides a 120-second grace period after death during which one can be rescued. To do this it cancels LivingDeathEvent and adds it's own handling. However, it seems No.-Lives gets to the event first and removes a life before the event is canceled. Thus this can be solved by lowering the event priority in EventHandler.

**Comment by thebrightspark** [comment]
Well the events visit mods in modId alphabetical order... So in theory presuming that other mod is on highest priority then it should get the event first (presuming its modId starts with "h").

I can lower the priority to High if it's necessary though.

**Comment by thebrightspark** [comment]
Just FYI that I do have the LifeLossEvent that's fired when a life is deducted from someone

**Comment by build2stone** [comment]
(I'm not the mod author, just making a pack with both mods)

I tested with the priority set to high earlier, and that seemed to work just fine.
I think this is happening because Hardcore Revival runs some checks before cancelling the event.
[Here](https://github.com/blay09/HardcoreRevival/blob/master/src/main/java/net/blay09/mods/hardcorerevival/handler/DeathHandler.java)'s the file in question.

**Comment by thebrightspark** [comment]
Ah alright, thanks 😄

**Comment by thebrightspark** [comment]
Fixed in commit https://github.com/thebrightspark/No.-Lives/commit/cbdae6c34e487c60ed23a402e7866f88bc8f37b3
