### ISSUE TITLE
Cannot seem to add lives via console commands. 1.12.2

### ISSUE THREAD

**Issue by Teirdalin** [thebrightspark/No.-Lives#5]
Typing lives add Teirdalin 1,  or sub 1,  or just about anything relating to lives including list into the server console doesn't seem to do anything.

**Comment by thebrightspark** [comment]
Sorry I didn't see this issue before. If this is still a problem, can you provide more details with the exact scenario of how this happens?

**Comment by thebrightspark** [comment]
Not sure if it was the issue, but I think I found an inconsistency between the code and the documented usage of the commands. Presuming this was the issue, I'm closing this as it should be fine for the next release.
