### ISSUE TITLE
[Feature Request] @p support for adding lives via commands

### ISSUE THREAD

**Issue by mr-poyo** [thebrightspark/No.-Lives#6]
Hello,

Is it possible to add the @p support for adding/removing lives via command line? I'm trying  to use this as a FTB Quests reward via commands, but unfortunately, it doesn't recognize the @p wildcard for player.

**Comment by thebrightspark** [comment]
On the mod page, I have it documented that you can specify the player in the existing command:
`/lives <add|sub|set> [playerName] <amount>`

**Comment by mr-poyo** [comment]
Is there a wildcard variable for player names? For a command block for example. If i use @p it creates a profile for a player named '@p'

`/lives add @p 1`

I've only figured out how to use it if i use exact player name, but for my modpack, i wouldn't know other people's names.

I could just give @p the nolives:heart but i was trying to uniform my rewards through commands. If not, it's ok.

**Comment by thebrightspark** [comment]
Ohhhh right I see now. I'll have a look into it and see what I can do.

**Comment by thebrightspark** [comment]
Sorry it's been such a long time... Been busy with other projects, but I've found the time to sort this!
![image](https://user-images.githubusercontent.com/11932411/63366082-dcd1c800-c370-11e9-8dc3-57ff2f940c09.png)

Will be in the next release.
