### ISSUE TITLE
Issue with Sync mod, not working as intended.

### ISSUE THREAD

**Issue by Forcefulmocha6** [thebrightspark/No.-Lives#7]
When using in conjunction with the Sync mod by IChun, if you die as a shell it still counts as a player death when it shouldn't count. Therefore making the whole idea of using the shells pointless.

**Comment by thebrightspark** [comment]
So as I suspected, No. Lives has a higher priority in handling deaths than Sync, as can be seen here in the Sync source:
https://github.com/iChun/Sync/blob/master/src/main/java/me/ichun/mods/sync/common/core/EventHandlerServer.java#L112-L113

Mine is handling with a priority of `HIGH`, so I will have to lower it to `LOW` to ensure it happens before that. Hopefully doing that won't break any other mod compatibility!

**Comment by thebrightspark** [comment]
Fixed this in commit https://github.com/thebrightspark/No.-Lives/commit/039ba80add2a75f711e5a0f1605caff3f4115013 for the next release.

**Comment by thebrightspark** [comment]
Oops got it wrong and my previous "fix" wasn't sufficient as Sync doesn't cancel the event.
Made the further fix here: https://github.com/thebrightspark/No.-Lives/commit/cc95f9bf6c7ad9e4928c0162d7e7fc4c00843d18
