### ISSUE TITLE
[Suggestion] Temp ban (timed)

### ISSUE THREAD

**Issue by mr-poyo** [thebrightspark/No.-Lives#9]
Hello again,

Thank you for a fun mod. I currently use it on my server, and was wondering if it would be hard to implement a temp-ban? A ban that would essentially expire and restore lives (to default?). The hard part might be that their lives would still be at 0 when they're unbanned, so they wouldn't be able to join the server. Not sure if this is possible, but thought i'd ask! Thank you!

**Comment by mr-poyo** [comment]
Just thought of how you could implement this.
I am able to add lives to users even if they're offline/banned.
if this feature were turned on, you could:

1) ban player with %time% expiration time (in banned-players.json file) then
2) immediately run 'lives set @p %default_value%' which is the starting lives in config.

This would allow users to login after expiration and start with default # lives.

**Comment by thebrightspark** [comment]
Hey, thanks for the suggestion! However this is a _rather_ specific feature that I'm not sure I'd like within the mod.

I'm sure someone could probably make an addon mod to do that (and they can feel free to come to me about anything they need exposing within this mod to make it work) for you if you can find someone willing to do it.

Sorry, hope you understand!
